### ISSUE TITLE
json fixtures not found

### ISSUE THREAD

**Issue by sectore** [billtrik/karma-fixture#10] opened 2015-06-05 17:52 UTC
There is an issue to use [karma-json-fixtures-preprocessor](https://github.com/dmitriiabramov/karma-json-fixtures-preprocessor/pull/3) as a preprocessor. `karma-json-fixtures-preprocessor` removes the `json` extension from `file.path` by default, which is needed to detect `json` files by `karma-fixture` https://github.com/billtrik/karma-fixture/blob/master/src/fixture.coffee#L49 

There is already an pull request at `karma-json-fixtures-preprocessor`
https://github.com/dmitriiabramov/karma-json-fixtures-preprocessor/pull/3

**Comment by sectore** [comment] 2015-06-17 07:04
To fix this issue just use latest version (v.0.0.4) of `karma-json-fixtures-preprocessor` and setup it by using the new feature `transformPath`:

```
jsonFixturesPreprocessor: {
  variableName: '__json__',
  transformPath: function(path) {
    return path + '.js';
  }
},
```

@billtrik: Could you update the instruction of "[setup the karma-json-fixtures-preprocessor plugin](https://github.com/billtrik/karma-fixture#installation)" for using `transformPath`, please? After this, this issue can be closed ;) Thanks!

**Comment by billtrik** [comment] 2017-01-20 13:24
Hey @sectore, @MarcusVeres, i am trying to reproduce this but i cannot.
Let me add here that you did not provide enough info about the problem, 
but instead only a proposed solution.

So, some background first:

Due to https://github.com/billtrik/karma-fixture/issues/7, i started using the `json-fixtures-preprocessor` to load JSON files.

This preprocessor works by loading every file declared here: 
```
preprocessors: {
  ...
   'test/fixtures/**/*.json'   : ['json_fixtures']
},
```

into the `window.__json__` object in the test page.
For every json file loaded from the filesystem, it creates a key in this object like: `"test/fixtures/some_other_folder/json_fixture_filename"` and the value is the contents of that file. 

Note that the key does not include the '.json' suffix, as described in the problem. I checked every published version and i also used the mentioned `transformPath` helper,
but it always does the same. 
The key is always without the '.json' suffix.

Pretty straight forward stuff.

In this commit:
https://github.com/billtrik/karma-fixture/commit/68bb7173c578a31daa316e47327305e6bcbfab39#diff-8d54b9a926c8d58538fac64c9aeefef7R50
i search for the requested json file trying out multiple combinations for the key string.

Specifically if you do a `fixture.load('json_fixture.json');` 
the plugin with try the following keys on the `__json__` object:

- `json_fixture`
- `json_fixture.json`
- `base/json_fixture`
- `base/json_fixture.json`
- `/absolute_fixture_path`

So in my setup, 
having done `fixture.setBase('base');` and then `fixture.load('json_fixture.json');` 
the requested json exists in `window.__json__['base/json_fixture']`.

So in my mind, i cannot see where the problem might be.

Since @MarcusVeres has the same issue though, maybe there is something else here.

Prior to anything, please double check that you are using the latest version of karma-fixture.

Then put a debugger before your `fixture.load()` line and check the key in the `window.__json__` object. It's keys should include the base and then the filename without the '.json' suffix. 
If not, maybe you have issues with how you declare which files to load in your config file.

If you still have a problem, please try to describe it as best as you can.
Finally since this is open source, it goes without saying that you are more than welcome to make a PR with a solution to this problem.

**Comment by billtrik** [comment] 2017-01-20 13:24
I am closing this for now. 
Will reopen it if there are still issues.

**Closed as completed by billtrik** 2017-01-20 13:24 UTC
